server:
  port: 8081

spring:
  datasource:
    username: test
    url: jdbc:mysql://localhost:3306/products?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    password: test
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq